/** IPC 通道协议（主进程 ↔ 渲染进程的唯一数据通道定义）。 */

export const IPC = {
  WorksList: 'works:list',
  WorksCreate: 'works:create',
  WorksRename: 'works:rename',
  WorksDelete: 'works:delete',
  ChaptersList: 'chapters:list',
  ChaptersCreate: 'chapters:create',
  ChaptersSave: 'chapters:save',
  ChaptersRename: 'chapters:rename',
  ChaptersDelete: 'chapters:delete',
  ChaptersRead: 'chapters:read',
  VolumesList: 'volumes:list',
  VolumesCreate: 'volumes:create',
  VolumesRename: 'volumes:rename',
  VolumesDelete: 'volumes:delete',
  VolumesReorder: 'volumes:reorder',
  VolumesSetChapters: 'volumes:set-chapters',
  TimelineList: 'timeline:list',
  TimelineSave: 'timeline:save',
  TimelineDelete: 'timeline:delete',
  TimelineReorder: 'timeline:reorder',
  SettingsGet: 'settings:get',
  SettingsSet: 'settings:set',
  WindowShow: 'window:show',
  ToolsTopmostSet: 'tools:topmost-set',
  TyperStart: 'typer:start',
  TyperStop: 'typer:stop',
  TyperState: 'typer:state',
  ClipboardSetEnabled: 'clipboard:set-enabled',
  ClipboardPush: 'clipboard:push',
  ClipboardRead: 'clipboard:read',
  ImportMarkdown: 'import:markdown',
  ExportSave: 'export:save',
  ExportPdf: 'export:pdf',
  ExportEpub: 'export:epub',
  ExportDocx: 'export:docx',
  NotesList: 'notes:list',
  NotesSave: 'notes:save',
  NotesDelete: 'notes:delete',
  NotesDeleteBatch: 'notes:delete-batch',
  NotesDeleteLogs: 'notes:delete-logs',
  SearchQuery: 'search:query',
  VersionsSave: 'versions:save',
  VersionsList: 'versions:list',
  VersionsRead: 'versions:read',
  PluginsList: 'plugins:list',
  OutlinesList: 'outlines:list',
  OutlinesSave: 'outlines:save',
  OutlinesDelete: 'outlines:delete',
  OutlinesReorder: 'outlines:reorder',
  ChapterOutlinesList: 'chapter-outlines:list',
  ChapterOutlinesSave: 'chapter-outlines:save',
  ChapterOutlinesDelete: 'chapter-outlines:delete',
  ChapterOutlinesExtract: 'chapter-outlines:extract',
  ChapterOutlinesExtractProgress: 'chapter-outlines:extract-progress',
  MindMapGet: 'mindmap:get',
  MindMapSave: 'mindmap:save',
  MindMapImport: 'mindmap:import',
  QuotaGet: 'quota:get',
  AppVersion: 'app:version',
  StatsTotals: 'stats:totals'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
